packages:
  - apps/*
  - packages/*

overrides:
  lodash: 4.18.1

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - lmdb
  - msgpackr-extract

allowBuilds:
  '@firebase/util': false
  '@parcel/watcher': true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
  protobufjs: false
