import type { CurriculumCopyKey, DemoProfileId, UiCopy } from './types.js';

export const requiredCopyKeys = [
  'appName',
  'tagline',
  'trainingSimulation',
  'liveModelOutput',
  'curatedFallback',
  'seededStartingState',
  'diagnosticHeading',
  'diagnosticPrompt',
  'confidencePrompt',
  'confidenceLow',
  'confidenceHigh',
  'routeHeading',
  'routeWhy',
  'quickRoute',
  'deepRoute',
  'lowEnergyRoute',
  'scaffoldHeading',
  'scaffoldOne',
  'scaffoldTwo',
  'scaffoldThree',
  'scaffoldFour',
  'scaffoldFive',
  'simulateHeading',
  'transferHeading',
  'teachBackHeading',
  'teachBackPrompt',
  'teachBackCorrect',
  'teachBackPartial',
  'teachBackMisconception',
  'teachBackMissingLink',
  'teachBackQuestion',
  'memoryRadarHeading',
  'memoryEstimateLabel',
  'memoryAssumptions',
  'evidenceHeading',
  'pauseAndVerify',
  'continue',
  'chooseDifferentRoute',
  'resetConcept',
  'fallbackSentence',
  'noSecrets',
  'noActiveLinks',
  'profileSavita',
  'profileArjun',
  'profileRamesh',
] as const satisfies readonly CurriculumCopyKey[];

const fallbackSentence =
  'Curated fallback used because the live model was unavailable or its output was rejected.';

export const uiCopy = {
  hi: {
    appName: 'सुरक्षा सूत्र',
    tagline: 'डिजिटल सुरक्षा सीखें, अपनी गति से',
    trainingSimulation: 'TRAINING SIMULATION',
    liveModelOutput: 'Live model output',
    curatedFallback: 'Curated fallback',
    seededStartingState: 'Seeded starting state',
    diagnosticHeading: 'पहले एक छोटी जाँच',
    diagnosticPrompt: 'अगर कोई संदेश पैसे पाने के लिए भुगतान की अनुमति माँगे, तो आप क्या करेंगे?',
    confidencePrompt: 'अपने जवाब पर आपका भरोसा कितना है?',
    confidenceLow: 'थोड़ा भरोसा',
    confidenceHigh: 'पूरा भरोसा',
    routeHeading: 'आपके लिए अगला रास्ता',
    routeWhy: 'यह सुझाव आपके अभी दर्ज जवाब, भरोसे और जाँच के इतिहास पर आधारित है।',
    quickRoute: 'Quick Route — छोटा अभ्यास',
    deepRoute: 'Deep Route — समझ, उदाहरण और नई स्थिति',
    lowEnergyRoute: 'Low-Energy Route — एक उदाहरण और दो छोटे सवाल',
    scaffoldHeading: 'सहायता का स्तर चुनें',
    scaffoldOne: 'पूरा उदाहरण देखें',
    scaffoldTwo: 'हर कदम का कारण समझें',
    scaffoldThree: 'कुछ खाली कदम भरें',
    scaffoldFour: 'ज़रूरत पर संकेत लेकर हल करें',
    scaffoldFive: 'नई स्थिति में आज़माएँ',
    simulateHeading: 'काल्पनिक स्थिति का अभ्यास',
    transferHeading: 'अब वही बात नई स्थिति में',
    teachBackHeading: 'अपनी भाषा में समझाएँ',
    teachBackPrompt: 'पैसे की दिशा और स्वतंत्र जाँच के बारे में दो वाक्य लिखें।',
    teachBackCorrect: 'सही बात',
    teachBackPartial: 'अधूरी कड़ी',
    teachBackMisconception: 'सुधार की ज़रूरत वाली धारणा',
    teachBackMissingLink: 'छूटी हुई कड़ी',
    teachBackQuestion: 'एक अगला सवाल',
    memoryRadarHeading: 'Memory Radar — अगली याद',
    memoryEstimateLabel: 'भविष्य की याद का अनुमान',
    memoryAssumptions: 'अनुमान दर्ज अभ्यास, सही जवाब, भरोसे और अगली समीक्षा की तारीख पर आधारित है।',
    evidenceHeading: 'System Evidence Drawer',
    pauseAndVerify: 'रुकें और स्वतंत्र जाँच करें',
    continue: 'आगे बढ़ें',
    chooseDifferentRoute: 'दूसरा रास्ता चुनें',
    resetConcept: 'इस अवधारणा को रीसेट करें',
    fallbackSentence,
    noSecrets: 'पासवर्ड, OTP या PIN कभी साझा न करें।',
    noActiveLinks: 'यह प्रशिक्षण है; इसमें कोई सक्रिय लिंक या असली खाता नहीं है।',
    profileSavita: 'सविता — सरल हिंदी',
    profileArjun: 'अर्जुन — Hinglish',
    profileRamesh: 'रमेश — हिंदी + English',
  },
  en: {
    appName: 'SurakshaSutra',
    tagline: 'Learn digital safety at your pace',
    trainingSimulation: 'TRAINING SIMULATION',
    liveModelOutput: 'Live model output',
    curatedFallback: 'Curated fallback',
    seededStartingState: 'Seeded starting state',
    diagnosticHeading: 'Start with a short check',
    diagnosticPrompt:
      'If a message asks for a payment authorisation to receive money, what will you do?',
    confidencePrompt: 'How confident are you in your answer?',
    confidenceLow: 'Not very confident',
    confidenceHigh: 'Very confident',
    routeHeading: 'Your next route',
    routeWhy:
      'This recommendation uses your recorded answer, confidence, and verification history.',
    quickRoute: 'Quick Route — short targeted practice',
    deepRoute: 'Deep Route — explanation, example, and a new context',
    lowEnergyRoute: 'Low-Energy Route — one example and two short questions',
    scaffoldHeading: 'Choose your support level',
    scaffoldOne: 'Observe a complete example',
    scaffoldTwo: 'Explain why each step exists',
    scaffoldThree: 'Complete selected missing steps',
    scaffoldFour: 'Solve with optional hints',
    scaffoldFive: 'Transfer to a new context',
    simulateHeading: 'Practise a fictional situation',
    transferHeading: 'Now use the same idea in a new setting',
    teachBackHeading: 'Explain it in your own words',
    teachBackPrompt: 'Write two sentences about payment direction and independent verification.',
    teachBackCorrect: 'Correct claim',
    teachBackPartial: 'Partial link',
    teachBackMisconception: 'Misconception to correct',
    teachBackMissingLink: 'Missing link',
    teachBackQuestion: 'One next question',
    memoryRadarHeading: 'Memory Radar — next review',
    memoryEstimateLabel: 'Estimated future recall',
    memoryAssumptions:
      'This estimate uses recorded practice, correctness, confidence, and the next review date.',
    evidenceHeading: 'System Evidence Drawer',
    pauseAndVerify: 'Pause and verify independently',
    continue: 'Continue',
    chooseDifferentRoute: 'Choose a different route',
    resetConcept: 'Reset this concept',
    fallbackSentence,
    noSecrets: 'Never share a password, OTP, or PIN.',
    noActiveLinks: 'This is training; it contains no active links or real accounts.',
    profileSavita: 'Savita — simple Hindi',
    profileArjun: 'Arjun — Hinglish',
    profileRamesh: 'Ramesh — Hindi + English',
  },
  hinglish: {
    appName: 'SurakshaSutra',
    tagline: 'Digital safety apni pace par seekho',
    trainingSimulation: 'TRAINING SIMULATION',
    liveModelOutput: 'Live model output',
    curatedFallback: 'Curated fallback',
    seededStartingState: 'Seeded starting state',
    diagnosticHeading: 'Short check se start karo',
    diagnosticPrompt:
      'Agar message money receive karne ke liye payment authorisation maange, to kya karoge?',
    confidencePrompt: 'Apne answer par kitna confidence hai?',
    confidenceLow: 'Thoda confidence',
    confidenceHigh: 'Full confidence',
    routeHeading: 'Tumhara next route',
    routeWhy:
      'Recommendation tumhare recorded answer, confidence aur verification history se aayi hai.',
    quickRoute: 'Quick Route — short targeted practice',
    deepRoute: 'Deep Route — explanation, example aur new context',
    lowEnergyRoute: 'Low-Energy Route — one example aur two short questions',
    scaffoldHeading: 'Support level choose karo',
    scaffoldOne: 'Complete example observe karo',
    scaffoldTwo: 'Har step kyun hai, explain karo',
    scaffoldThree: 'Selected missing steps complete karo',
    scaffoldFour: 'Optional hints ke saath solve karo',
    scaffoldFive: 'New context mein transfer karo',
    simulateHeading: 'Fictional situation practise karo',
    transferHeading: 'Ab same idea ko new setting mein use karo',
    teachBackHeading: 'Apne words mein explain karo',
    teachBackPrompt: 'Payment direction aur independent verification par do sentences likho.',
    teachBackCorrect: 'Correct claim',
    teachBackPartial: 'Partial link',
    teachBackMisconception: 'Correct karne wali misconception',
    teachBackMissingLink: 'Missing link',
    teachBackQuestion: 'One next question',
    memoryRadarHeading: 'Memory Radar — next review',
    memoryEstimateLabel: 'Estimated future recall',
    memoryAssumptions:
      'Estimate recorded practice, correctness, confidence aur next review date use karta hai.',
    evidenceHeading: 'System Evidence Drawer',
    pauseAndVerify: 'Pause karo aur independently verify karo',
    continue: 'Continue',
    chooseDifferentRoute: 'Different route choose karo',
    resetConcept: 'Is concept ko reset karo',
    fallbackSentence,
    noSecrets: 'Password, OTP ya PIN kabhi share mat karo.',
    noActiveLinks: 'Ye training hai; isme active links ya real accounts nahi hain.',
    profileSavita: 'Savita — simple Hindi',
    profileArjun: 'Arjun — Hinglish',
    profileRamesh: 'Ramesh — Hindi + English',
  },
  hi_en: {
    appName: 'SurakshaSutra',
    tagline: 'Digital safety अपनी pace पर सीखें',
    trainingSimulation: 'TRAINING SIMULATION',
    liveModelOutput: 'Live model output',
    curatedFallback: 'Curated fallback',
    seededStartingState: 'Seeded starting state',
    diagnosticHeading: 'एक short check से शुरू करें',
    diagnosticPrompt:
      'अगर message money receive करने के लिए payment authorisation माँगे, तो आप क्या करेंगे?',
    confidencePrompt: 'अपने answer पर confidence कितना है?',
    confidenceLow: 'थोड़ा confidence',
    confidenceHigh: 'Full confidence',
    routeHeading: 'आपका next route',
    routeWhy:
      'यह recommendation आपके recorded answer, confidence और verification history से आती है।',
    quickRoute: 'Quick Route — short targeted practice',
    deepRoute: 'Deep Route — explanation, example और new context',
    lowEnergyRoute: 'Low-Energy Route — one example और two short questions',
    scaffoldHeading: 'Support level choose करें',
    scaffoldOne: 'Complete example observe करें',
    scaffoldTwo: 'हर step का reason explain करें',
    scaffoldThree: 'Selected missing steps complete करें',
    scaffoldFour: 'Optional hints के साथ solve करें',
    scaffoldFive: 'New context में transfer करें',
    simulateHeading: 'Fictional situation practise करें',
    transferHeading: 'अब same idea को new setting में use करें',
    teachBackHeading: 'अपने words में explain करें',
    teachBackPrompt: 'Payment direction और independent verification पर दो sentences लिखें।',
    teachBackCorrect: 'Correct claim',
    teachBackPartial: 'Partial link',
    teachBackMisconception: 'Correct करने वाली misconception',
    teachBackMissingLink: 'Missing link',
    teachBackQuestion: 'One next question',
    memoryRadarHeading: 'Memory Radar — next review',
    memoryEstimateLabel: 'Estimated future recall',
    memoryAssumptions:
      'यह estimate recorded practice, correctness, confidence और next review date पर आधारित है।',
    evidenceHeading: 'System Evidence Drawer',
    pauseAndVerify: 'Pause करें और independently verify करें',
    continue: 'Continue',
    chooseDifferentRoute: 'Different route choose करें',
    resetConcept: 'इस concept को reset करें',
    fallbackSentence,
    noSecrets: 'Password, OTP या PIN कभी share न करें।',
    noActiveLinks: 'यह training है; इसमें active links या real accounts नहीं हैं।',
    profileSavita: 'Savita — simple Hindi',
    profileArjun: 'Arjun — Hinglish',
    profileRamesh: 'Ramesh — Hindi + English',
  },
} as const satisfies Readonly<Record<'hi' | 'en' | 'hinglish' | 'hi_en', UiCopy>>;

export const copyByLanguage = uiCopy;
export const copyCatalog = uiCopy;

export const profileCopy: Readonly<Record<DemoProfileId, UiCopy>> = {
  'profile-savita': uiCopy.hi,
  'profile-arjun': uiCopy.hinglish,
  'profile-ramesh': uiCopy.hi_en,
};

export const copyByProfile = profileCopy;

export { fallbackSentence };
